### PR TITLE
Moved template function to puppet class in order to allow hiera data spe...

### PR DESCRIPTION
**Pull request by predicador37**
...cification.

I have tested this change and now hiera can be used, just in case you're interested in including it.

### CODE REVIEW

**Comment by predicador37** [comment]
The checks probably fail because content variable must be assigned the path of the template in hiera, ie:

      varnish_vcl:
        '/etc/varnish/default.vcl':
        content: 'profile/varnish.erb'

`profile/varnish.erb` is the path to my varnish vcl file.

**Comment by bashtoni** [comment]
Hi,

I don't quite understand this pull request.  

You seem to have changed the meaning of content - currently it expects that the computed template should be passed in, but your yaml snippet suggests you want to pass in the template filename.

Am I correct in thinking what you want to be able to do is specify a hash of vcl files to be created in hiera, and then use `create_resources`?

**Comment by predicador37** [comment]
Yes... sorry, perhaps this is not the best way to do it. In MOTD module the field is named "template", not content.

**Comment by bashtoni** [comment]
Hi, closing this as per comments.

**Pull request closed without merging**
