### PR TITLE
Add 'stretch and above support', 'new gpgkeys for 62 63' and 'fix systemd unit file'

### PR DESCRIPTION
**Pull request by NITEMAN**
Superseeds #67 fixing an error on template

### CODE REVIEW

**Comment by fe80** [comment]
Hello @NITEMAN 

Like I ask in #65 can you add test for the service file content ?

I need to upgrade pdk and review all test, maybe you I can look that before and you can rebase with the master for pull all test

**Comment by NITEMAN** [comment]
Ok, please ping me when updates are on master and I'll rebase, swtich to modern facts and try to add some tests for the service file

**Comment by fe80** [comment]
Hello @NITEMAN ,

I've fix and update the ci, but I've add breaking about the puppet version support (drop puppet 4/5 and add 7).

I've also fix all legacy fact, can you please rebase from the master ? It's maybe better to create 2 news pull request with the  feature and the bug

**Comment by NITEMAN** [comment]
OK @fe80 , I'll try to do it next week

**Comment by NITEMAN** [comment]
Superseeded by #74 & #75

**Pull request closed without merging**
