### PR TITLE
Updated module to support Varnish 4 for Ubuntu 14

### PR DESCRIPTION
**Pull request by pawosty**
- Added tests
- Updated docs

### CODE REVIEW

**Comment by pawosty** [comment]
Looks like the all tests are failing for Puppet 3.2/ & 3.3, but I can't figure out why. I'm trying to set up something locally to test.

**Comment by dougneal** [comment]
:+1: with a trivial change this could cover Varnish 3 on 14.04 too. See https://github.com/BashtonLtd/puppet-varnish/pull/13

**Comment by bashtoni** [comment]
Thanks, great to see you've written tests too :)

**Comment by pawosty** [comment]
Glad to help! @dougneal I'm not sure what happened to cause some tests to fail in your branch, but yeah - Varnish 3 on Ubuntu 14.04 would work, as should Varnish 4 on Ubuntu 12.

**Comment by dougneal** [comment]
Yeah, I've killed my branch as this is a much better effort! I'm now using this and setting `varnish_version => '3.0'` and `addrepo => false` and it looks good. There could be a question of whether the module should default to 3.0 (with native packages) or 4.0 (with upstream packages), on one hand it defaults to upstream packages on Red Hat, on the other it doesn't for Ubuntu 12.04 but any careful user will be explicit about it anyway.

**Pull request merged**
